{% set name = "seabreeze" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be8f327a606eb759ec02703fb53ac2e1c877700ea6504b0cc97f32e962b27954

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - seabreeze_os_setup = seabreeze.os_setup:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - setuptools_scm
    - pkgconfig
    - libusb-compat  # [linux]
    - pytest-runner
  run:
    - python
    - libusb-compat  # [linux]
    - numpy
    - pyusb
    - typing_extensions  # [py<38]

test:
  imports:
    - seabreeze
    - seabreeze.types
    - seabreeze.cseabreeze
    - seabreeze.pyseabreeze
  requires:
    - pytest
    - mock
  source_files:
    - tests
  commands:
    - pytest -v tests/

about:
  home: https://github.com/ap--/python-seabreeze
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Python module for Ocean Optics spectrometer
  dev_url: https://github.com/ap--/python-seabreeze
  doc_url: https://python-seabreeze.readthedocs.io

extra:
  recipe-maintainers:
    - ap--
